### ISSUE TITLE
Configure sslmode of postgres scheme

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry/cf-networking-helpers#3]
Applied ops to deploy cf which introduced policy server:

```
    - type: replace
      path: /instance_groups/name=api/jobs/name=policy-server/properties/database
      value:
        ca_cert: ((icd_pg.certificate))
        host: ((icd_pg.host))
        name: network_policy
        password: ((network_policy_database_password))
        port: ((icd_pg.port))
        require_ssl: true
        type: postgres
        username: network_policy
```

But if db server had restricted ssl mode, policy-server `pre-start` failed at:

```
{"timestamp":"2019-08-23T05:49:09.182817473Z","level":"info","source":"cfnetworking.policy-server-migrate-db","message":"cfnetworking.policy-server-migrate-db.getting migration db connection","data":{}}
{"timestamp":"2019-08-23T05:49:09.182901134Z","level":"info","source":"cfnetworking.policy-server-migrate-db","message":"cfnetworking.policy-server-migrate-db.getting db connection","data":{}}
{"timestamp":"2019-08-23T05:49:09.229089250Z","level":"error","source":"cfnetworking.policy-server-migrate-db","message":"cfnetworking.policy-server-migrate-db.failed migrating and populating tags, retrying","data":{"error":"getting migration db connection: cfnetworking.policy-server-migrate-db: db connect: unable to ping: pq: no pg_hba.conf entry for host \"172.30.164.243\", user \"network_policy\", database \"network_policy\", SSL off"}}
```

The reason is this package hardcoded `sslmod`:

https://github.com/cloudfoundry/cf-networking-helpers/blob/master/db/config.go#L28

We need that ssl mode can be configured.
